// Generated by CoffeeScript 2.2.4
(function() {
  var Animal, Horse, areaOfAquare, grade, horse, i, len, number, numbers, score;

  score = 83;

  grade = (function() {
    switch (false) {
      case !(score < 60):
        return 'E';
      case !(score < 70):
        return 'D';
      case !(score < 80):
        return 'C';
      case !(score < 90):
        return 'B';
      default:
        return 'A';
    }
  })();

  console.log(grade);

  areaOfAquare = function(s) {
    return s * s;
  };

  numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  console.log(numbers);

  for (i = 0, len = numbers.length; i < len; i++) {
    number = numbers[i];
    console.log("Number: " + number);
  }

  Animal = class Animal {
    constructor(name1) {
      this.name = name1;
    }

    move(meters) {
      return console.log(this.name + " moved " + meters + " meters.");
    }

  };

  Horse = class Horse extends Animal {
    constructor(name, type) {
      super(name);
    }

    neigh() {
      return console.log("Neighhh");
    }

  };

  horse = new Horse("Misty", "Arab Race Horse");

  horse.neigh();

  horse.move(500);

}).call(this);
